CamelCasePlugin option to maintainJson data format
koskimas/kysely pull request #284
Opened 2023-01-18 18:32 UTC by otaviosoares

closes #281

2023-01-20 10:50 UTC, igalklebanov requested changes
Hey 👋 

Thank you! 💪

2023-01-20 10:50 UTC, igalklebanov commented on test/node/src/camel-case.test.ts
> +        })
let's reuse `camelDb`..

```ts
camelDb.withoutPlugins().withPlugin(new CamelCasePlugin({ maintainJsonFormat: true }))
```

2023-01-20 10:50 UTC, igalklebanov commented on test/node/src/camel-case.test.ts
> +    if (dialect !== 'sqlite') {
could we cover sqlite as well? it's a `JSON.parse` or a an assertion against a string away..

2023-01-20 10:50 UTC, igalklebanov commented on test/node/src/camel-case.test.ts
> +        expect(data?.preferences).to.eql({
```suggestion
          .executeTakeFirstOrThrow()
          
        expect(data.preferences).to.eql({
```

2023-01-20 10:50 UTC, igalklebanov commented on test/node/src/camel-case.test.ts
> +        await dbWithOption.destroy()
no need if reusing `camelDb`.

2023-01-20 10:50 UTC, igalklebanov commented on src/plugin/camel-case/camel-case-plugin.ts
> +  opt?: CamelCasePluginOptions
```suggestion
  opt: CamelCasePluginOptions
```

2023-01-20 10:50 UTC, igalklebanov commented on src/plugin/camel-case/camel-case-plugin.ts
> +    !opt?.maintainJsonFormat
```suggestion
    !opt.maintainJsonFormat
```

2023-01-20 10:53 UTC, igalklebanov commented
@koskimas wondering if transformer should apply naming strategy recursively to json parameters, seems not aligned with output transformation logic.. WDYT?

2023-01-20 23:29 UTC, otaviosoares commented on test/node/src/camel-case.test.ts
> +        })
Thank, didn't know about that one

2023-01-20 23:55 UTC, igalklebanov approved these changes
LGTM! 🚀

2023-01-23 09:22 UTC, koskimas commented
`maintainJsonFormat` is not the best name for the option IMO. This doesn't just apply to JSON but any nested objects. A better name would be `maintainNestedObjectKeys`

2023-01-23 09:30 UTC, koskimas commented
> @koskimas wondering if transformer should apply naming strategy recursively to json parameters, seems not aligned with output transformation logic.. WDYT?

You mean essentially making this option `true` by default? The use case I was thinking when I implemented this wasn't only json object columns but `json_agg` etc. nested objects that would by default have snake_cased properties you'd also want to map.

I'm fine by changing the default, but It could be a nasty breaking change.

2023-01-24 09:10 UTC, koskimas commented
LGTM! Thank you @otaviosoares ❤️

2023-01-24 09:15 UTC, merged

2023-01-24 09:34 UTC, igalklebanov commented
> > @koskimas wondering if transformer should apply naming strategy recursively to json parameters, seems not aligned with output transformation logic.. WDYT?
> 
> You mean essentially making this option `true` by default? The use case I was thinking when I implemented this wasn't only json object columns but `json_agg` etc. nested subqueries that would by default have snake_cased properties you'd also want to map.
> 
> I'm fine with changing the default, but It could be a nasty breaking change.

Sorry, I meant that we seem to only alter identifiers on input, doing nothing to json parameters in value nodes. On output, we touch everything.

Makes you wonder, if for predictability, consumers would want the option that nested json keys have same naming strategy as columns.