(docs): Add inline left join examples
koskimas/kysely pull request #326
Opened 2023-02-11 18:19 UTC by maarteNNNN

2023-02-12 21:10 UTC, seveibar commented
i was doing some searching today on complex joins and this was really helpful!

2023-02-12 22:53 UTC, naorpeled approved these changes

2023-02-12 22:53 UTC, naorpeled commented
LGTM!

2023-02-12 23:04 UTC, igalklebanov requested changes
Thank you! 💪 

Not sure this is worth the maintenance, I believe it was left out for a reason (@koskimas correct me if I'm wrong). 
Wonder if this could be automated (copy `innerJoin` examples, replace occurences with `leftJoin`).

But anyway:

- Missing generated SQL code blocks for both examples.
- Should be pasted to other query builders with left join methods.

2023-02-13 13:55 UTC, maarteNNNN commented on src/query-builder/select-query-builder.ts
> +   *   .on('person.address_id', 'address.id')
Right... My bad, fixed in c6b706362ca8d912d97a1938dea8c4557799bbc2.

2023-02-13 13:57 UTC, maarteNNNN commented
> Not sure this is worth the maintenance

Let me know if this can/will go forward then I'll add the generated SQL and adapt all other query builders with left joins.

2023-02-15 18:14 UTC, koskimas commented
Yeah the examples were left out on purpose to reduce copy-pasta. There's a link to the `innerJoin` docs from all other join methods. The API is exactly the same for all join methods. Copy-pasting the examples to all methods doesn't make sense to me. They will diverge.

2023-02-15 18:18 UTC, koskimas commented
Should we make it more clear that you can find more documentation behind the link? Something like `For more info see the <a>innerJoin</a> docs`?

2023-02-15 18:23 UTC, closed without merging